### ISSUE TITLE
/playerinfo not working 

### ISSUE THREAD

**Issue by GreenManNumber1** [Blumlaut/EasyAdmin#354]
Error: An error occurred while calling export getPlayerWarnings of resource EasyAdmin - see above for details
    at Proxy.<anonymous> (citizen:/scripting/v8/main.js:548:15)
    at Object.execute (C:\FXServer\server-data\resources\EasyAdmin\server\bot\commands\playerinfo.js:49:76)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (@EasyAdmin/server/bot/bot.js:92:17)

**Comment by Blumlaut** [comment]
error should also include a trace for Lua, that's missing here, no way to trace the bug without that.
