### ISSUE TITLE
[BUG] Script Error in Event playerJoining & playerDropped

### ISSUE THREAD

**Issue by NoobSpielt** [Blumlaut/EasyAdmin#500]
**Describe the bug**
When a Player joines and leaves following errors appear in the Server Console
```
[    script:EasyAdmin] SCRIPT ERROR in event `playerJoining': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:6)
```
and 
```
[    script:EasyAdmin] SCRIPT ERROR in event `playerDropped': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:23)
```
**To Reproduce**
1. Join or leave the Server
2. See error

**Expected behavior**
No Error.

**Screenshots/Logs**
```
[      script:hardcap] Connecting: Marvin_Plays
[    script:EasyAdmin] SCRIPT ERROR in event `playerJoining': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:6)
[    script:EasyAdmin] 
```

**Server Infos (please complete the following information):**
 - OS: Red Hat Enterprise Linux release 8.6 (Ootpa)
 - FXServer Version 5715
 - EasyAdmin Version 6.9

**Additional context**

**Comment by NoobSpielt** [comment]
This does not affect Easyadmin in any way. The Bug just appears in the console

**Comment by Blumlaut** [comment]
> EasyAdmin is not defined

assuming you are **not** using the Discord Bot?

**Comment by Blumlaut** [comment]
Then it looks like the bot didn't initialise properly, `EasyAdmin` is a placeholder for GetCurrentResourceName() which only gets set once the Discord Bot comes online

**Comment by NoobSpielt** [comment]
Just checked it. You are right. The Discord Bot is not initialising, becouse of some missing node modules.

 I'm not really familier with yarn. Is there a possibilty to force a new build without reinstalling EasyAdmin?

**Comment by Blumlaut** [comment]
> Is there a possibilty to force a new build without reinstalling EasyAdmin

deleting the `.yarn.installed` and `yarn.lock` files should be fine

**Comment by NoobSpielt** [comment]
> > Is there a possibilty to force a new build without reinstalling EasyAdmin
> 
> deleting the `.yarn.installed` and `yarn.lock` files should be fine

Thanks for that. It did do a new build. But for a weird reason even after that the node module "juration" is missing.


this is the Error log:
```
> ensure EasyAdmin
[ citizen-server-impl] Stopping resource EasyAdmin
[    c-scripting-core] Creating script environments for EasyAdmin
[    script:EasyAdmin] Error loading script server/bot/bot.js in resource EasyAdmin: Error: Cannot find module 'juration'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - /home/fivem/FXServer/server-data/resources//[admin]/EasyAdmin/dummy.js
[    script:EasyAdmin] stack:
[    script:EasyAdmin] Error: Cannot find module 'juration'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - /home/fivem/FXServer/server-data/resources//[admin]/EasyAdmin/dummy.js
[    script:EasyAdmin]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[    script:EasyAdmin]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[    script:EasyAdmin]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[    script:EasyAdmin]     at require (node:internal/modules/cjs/helpers:94:18)
[    script:EasyAdmin]     at @EasyAdmin/server/bot/bot.js:11:12
[    c-scripting-core] Failed to load script server/bot/bot.js.
[    script:EasyAdmin] Error loading script server/bot/chat_bridge.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/chat_bridge.js:67:1
[    c-scripting-core] Failed to load script server/bot/chat_bridge.js.
[    script:EasyAdmin] Error loading script server/bot/roles.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/roles.js:35:5
[    c-scripting-core] Failed to load script server/bot/roles.js.
[    script:EasyAdmin] Error loading script server/bot/server_status.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/server_status.js:130:1
[    c-scripting-core] Failed to load script server/bot/server_status.js.
[ citizen-server-impl] Started resource EasyAdmin
```

**Comment by Blumlaut** [comment]
try deleting your server's yarn cache and delete easyadmin's node_modules folder alongside the other two files, not sure why the module would be missing

**Comment by NoobSpielt** [comment]
Thanks, that did work. Still weird why it didn't installed the module directly.
