### ISSUE TITLE
[BUG] Discord bug with 7.0?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [Blumlaut/EasyAdmin#709]
Updated to Release of 7.0
But now I'm getting this in relation to Discord but I'm not sure what to do or what to change between previous version and 7.0?

I tried reading the documentation but it seems outdated unfortunately.

```
[    script:EasyAdmin] Error: DiscordAPIError[10062]: Unknown interaction
[    script:EasyAdmin]     at handleErrors (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:640:13)
[    script:EasyAdmin]     at runMicrotasks (<anonymous>)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async BurstHandler.runRequest (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:736:23)
[    script:EasyAdmin]     at async REST.request (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1387:22)
[    script:EasyAdmin]     at async ChatInputCommandInteraction.reply (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:111:5)
[    script:EasyAdmin]     at async Object.execute (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\server\bot\commands\playerlist.js:53:3)
[    script:EasyAdmin]     at async Client.<anonymous> (@EasyAdmin/server/bot/bot.js:102:17)
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled rejection): DiscordAPIError[40060]: Interaction has already been acknowledged.
[    script:EasyAdmin] > handleErrors (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:640)
[    script:EasyAdmin] > runMicrotasks (<anonymous>:0)
[    script:EasyAdmin] > processTicksAndRejections (node:internal/process/task_queues:96)
[    script:EasyAdmin] > async BurstHandler.runRequest (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:736)
[    script:EasyAdmin] > async REST.request (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1387)
[    script:EasyAdmin] > async ChatInputCommandInteraction.reply (C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:111)
[    script:EasyAdmin] 
[        script:guard] [Info] [PhoenixAC] [Version Monitor]: Checking for new versions...
[        script:guard] [Info] [PhoenixAC] [Version Monitor]: No new versions found.
[    script:EasyAdmin] Uncaught Unknown interaction
[    script:EasyAdmin] C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js(338,5): DiscordAPIError
[    script:EasyAdmin] C:\FXServer_EOTS\txData\CFXDefault_0E6567.base\resources\EasyAdmin\node_modules\@discordjs\rest\dist\index.js(640,13): handleErrors
[    script:EasyAdmin] node:internal/process/task_queues(96,5): processTicksAndRejections
[    script:EasyAdmin] 
[    script:EasyAdmin] DiscordAPIError[10062]: Unknown interaction
```

Edit* Should remove botGuild convar from server cfg?

**Comment by Blumlaut** [comment]
closed due to missing repro steps.
