### ISSUE TITLE
Stack:

### ISSUE THREAD

**Issue by adorne1** [Blumlaut/EasyAdmin#719]
TypeError: isJSONEncodable is not a function
    at /home/zap966871/g553581/gta5-fivem-txadmin/CFXDefault_5078AB.base/resources/EasyAdmin/node_modules/discord.js/src/structures/MessagePayload.js:202:9
    at Array.map (<anonymous>)
    at MessagePayload.resolveBody (/home/zap966871/g553581/gta5-fivem-txadmin/CFXDefault_5078AB.base/resources/EasyAdmin/node_modules/discord.js/src/structures/MessagePayload.js:201:36)
    at ChatInputCommandInteraction.reply (/home/zap966871/g553581/gta5-fivem-txadmin/CFXDefault_5078AB.base/resources/EasyAdmin/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:109:56)
    at Object.execute (/home/zap966871/g553581/gta5-fivem-txadmin/CFXDefault_5078AB.base/resources/EasyAdmin/server/bot/commands/playerlist.js:53:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (@EasyAdmin/server/bot/bot.js:102:17)

**Comment by adorne1** [comment]
Renamed resourced on accident. Issue is solved.

**Comment by adorne1** [comment]
Nevermind!! still an issue: 
![image](https://user-images.githubusercontent.com/132327825/235586984-2ab66eeb-f5fe-48cf-a22a-2d0a3f9dc9e3.png)

**Comment by Blumlaut** [comment]
no info, no help.
