### ISSUE TITLE
Problem Discord player list

### ISSUE THREAD

**Issue by selnferreira** [Blumlaut/EasyAdmin#774]
Good afternoon. When I run the command to see the list of players I get this error, can you help me?

TypeError: user.identifiers is not iterable
    at getDiscordAccountFromPlayer (@EasyAdmin/server/bot/functions.js:82:30)
    at Object.execute (C:\Users\ruben\Desktop\esx_core-1.10.1\resources\[addons]\EasyAdmin\server\bot\commands\playerlist.js:86:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (@EasyAdmin/server/bot/bot.js:66:4)

**Comment by Blumlaut** [comment]
already fixed in https://github.com/Blumlaut/EasyAdmin/commit/9c00970b43fc2d4a345ebdfcc2ab26ab703be358

not available in any release yet.
