### ISSUE TITLE
EasyAdmin console error 

### ISSUE THREAD

**Issue by CamoTJC** [Blumlaut/EasyAdmin#792]
when server boots and loads easytadmin this error show 

`[  (node:5500) UnhandledPromiseRejectionWarning: TypeError: this.rest.clearHashSweeper is not a function
    at Client.destroy (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\client\BaseClient.js:47:15)
    at Client.destroy (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\client\Client.js:248:11)
    at Client.login (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\client\Client.js:229:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:5500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
  script:EasyAdmin] Caught exception:  TypeError: this.rest.clearHashSweeper is not a function
[    script:EasyAdmin]     at Client.destroy (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\client\BaseClient.js:47:15)
[    script:EasyAdmin]     at Client.destroy (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\client\Client.js:248:11)
[    script:EasyAdmin]     at Client.login (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\client\Client.js:229:18)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:5500) UnhandledPromiseRejectionWarning: DiscordAPIError[0]: 401: Unauthorized
    at SequentialHandler.runRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:933:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:712:14)
    at async REST.request (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1321:22)
    at async ChannelManager.fetch (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\managers\ChannelManager.js:123:18)
    at async updateServerStatus (@EasyAdmin/server/bot/server_status.js:89:16)
(node:5500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[    script:EasyAdmin] Caught exception:  DiscordAPIError[0]: 401: Unauthorized
[    script:EasyAdmin]     at SequentialHandler.runRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:933:15)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:712:14)
[    script:EasyAdmin]     at async REST.request (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1321:22)
[    script:EasyAdmin]     at async ChannelManager.fetch (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\managers\ChannelManager.js:123:18)
[    script:EasyAdmin]     at async updateServerStatus (@EasyAdmin/server/bot/server_status.js:89:16)`

`[    script:EasyAdmin] Caught exception:  Error: Expected token to be set for this request, but none was present
[    script:EasyAdmin]     at RequestManager.resolveRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1096:15)
[    script:EasyAdmin]     at RequestManager.queueRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1056:46)
[    script:EasyAdmin]     at REST.raw (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1330:32)
[    script:EasyAdmin]     at REST.request (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1321:33)
[    script:EasyAdmin]     at REST.get (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1257:17)
[    script:EasyAdmin]     at ChannelManager.fetch (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\managers\ChannelManager.js:123:41)
[    script:EasyAdmin]     at updateServerStatus (@EasyAdmin/server/bot/server_status.js:89:38)
[    script:EasyAdmin]     at Object.callback (citizen:/scripting/v8/timer.js:126:17)
[    script:EasyAdmin]     at onTick (citizen:/scripting/v8/timer.js:171:27)
[    script:EasyAdmin]     at citizen:/scripting/v8/timer.js:270:13(node:5500) UnhandledPromiseRejectionWarning: Error: Expected token to be set for this request, but none was present
    at RequestManager.resolveRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1096:15)
    at RequestManager.queueRequest (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1056:46)
    at REST.raw (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1330:32)
    at REST.request (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1321:33)
    at REST.get (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1257:17)
    at ChannelManager.fetch (C:\Users\Administrator\Desktop\txData\CFXDefaultFiveM_02533F.base\resources\[menus]\EasyAdmin\node_modules\discord.js\src\managers\ChannelManager.js:123:41)
    at updateServerStatus (@EasyAdmin/server/bot/server_status.js:89:38)
    at Object.callback (citizen:/scripting/v8/timer.js:126:17)
    at onTick (citizen:/scripting/v8/timer.js:171:27)
    at citizen:/scripting/v8/timer.js:270:13
(node:5500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
`

**Comment by Blumlaut** [comment]
> DiscordAPIError[0]: 401: Unauthorized 

Your Discord Bot token is invalid, or your Bot does not have the correct permissions set.

**Comment by CamoTJC** [comment]
yep worked that out.

now i updated my chat resource but still getting this error

![Screenshot 2023-09-16 224736](https://github.com/Blumlaut/EasyAdmin/assets/145170932/9125f372-8668-4225-9fd0-8034809d5d9e)
