### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Partyleonyt** [Blumlaut/EasyAdmin#810]
an Error when using from the bot the /playerlist command
TypeError: user.identifiers is not iterable
    at getDiscordAccountFromPlayer (@EasyAdmin/server/bot/functions.js:82:30)
    at Object.execute (C:\Users\Administrator\Desktop\universumlife\resourcen\resources\[Extra]\[Scripts]\[Adminmenu]\EasyAdmin\server\bot\commands\playerlist.js:86:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (@EasyAdmin/server/bot/bot.js:66:4)

**Comment by Blumlaut** [comment]
was fixed in https://github.com/Blumlaut/EasyAdmin/commit/9c00970b43fc2d4a345ebdfcc2ab26ab703be358
